language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install pytest pytest-console-scripts
  - pip install pytest-cov
  - pip install coveralls
install:
  - pip install -e .
script:
  - py.test --cov=fdt tests/*
after_success:
  - coveralls